// <auto-generated />
using System;
using ConsidTechnicalBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsidTechnicalBackend.Migrations
{
    [DbContext(typeof(ConsidContext))]
    partial class ConsidContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsidTechnicalBackend.Database.Models.DbCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("ConsidTechnicalBackend.Database.Models.DbEmployees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCEO")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IsCEO")
                        .IsUnique()
                        .HasFilter("[IsCEO] = 1");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            IsCEO = true,
                            IsManager = false,
                            LastName = "Doe",
                            Salary = 50m
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Alex",
                            IsCEO = false,
                            IsManager = true,
                            LastName = "Fernandez",
                            ManagerId = 1,
                            Salary = 25m
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jane",
                            IsCEO = false,
                            IsManager = true,
                            LastName = "Doe",
                            ManagerId = 2,
                            Salary = 20m
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Harry",
                            IsCEO = false,
                            IsManager = false,
                            LastName = "Andersson",
                            ManagerId = 2,
                            Salary = 12m
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Lucas",
                            IsCEO = false,
                            IsManager = false,
                            LastName = "Swan",
                            ManagerId = 2,
                            Salary = 15m
                        });
                });

            modelBuilder.Entity("ConsidTechnicalBackend.Database.Models.DbLibraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BorrowDate")
                        .HasColumnType("date");

                    b.Property<string>("Borrower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBorrowable")
                        .HasColumnType("bit");

                    b.Property<int?>("Pages")
                        .HasColumnType("int");

                    b.Property<int?>("RunTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LibraryItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "John Doe",
                            CategoryId = 1,
                            IsBorrowable = true,
                            Pages = 50,
                            Title = "The Short Man",
                            Type = "Book"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsBorrowable = true,
                            RunTimeMinutes = 120,
                            Title = "The Idiot",
                            Type = "DVD"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            IsBorrowable = true,
                            RunTimeMinutes = 100,
                            Title = "The Shark",
                            Type = "Audio Book"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Doe",
                            CategoryId = 3,
                            IsBorrowable = false,
                            Pages = 200,
                            Title = "The cooking book",
                            Type = "Reference Book"
                        });
                });

            modelBuilder.Entity("ConsidTechnicalBackend.Database.Models.DbLibraryItem", b =>
                {
                    b.HasOne("ConsidTechnicalBackend.Database.Models.DbCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
